
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3F610FE6299FE620D758E0D3D3758054'
    
_lr_action_items = {'AND':([1,2,3,13,15,16,17,19,27,28,30,],[-5,9,-7,-6,-2,-3,-4,9,-1,-9,-8,]),'CONSTANT':([0,4,6,7,8,9,11,12,14,18,29,],[5,10,5,5,5,5,5,24,10,24,24,]),'VARIABLE':([12,18,29,],[22,22,22,]),'IMPLY':([1,2,3,13,15,16,17,19,27,28,30,],[-5,7,-7,-6,-2,-3,-4,7,-1,-9,-8,]),'COMA':([20,21,22,23,24,25,26,31,],[29,-15,-10,-12,-11,-13,29,-14,]),'LPAREN':([4,5,10,],[11,12,18,]),'NOT':([0,6,7,8,9,11,],[4,14,14,14,14,4,]),'RPAREN':([1,3,13,15,16,17,19,20,21,22,23,24,25,26,27,28,30,31,],[-5,-7,-6,-2,-3,-4,27,28,-15,-10,-12,-11,-13,30,-1,-9,-8,-14,]),'OR':([1,2,3,13,15,16,17,19,27,28,30,],[6,8,-7,-6,6,6,6,8,-1,-9,-8,]),'$end':([1,2,3,13,15,16,17,27,28,30,],[-5,0,-7,-6,-2,-3,-4,-1,-9,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'clause':([0,7,8,9,11,],[1,15,16,17,1,]),'argus':([12,18,],[20,26,]),'argu':([12,18,29,],[21,21,31,]),'cnf':([0,11,],[2,19,]),'atom':([0,6,7,8,9,11,],[3,13,3,3,3,3,]),'var':([12,18,29,],[23,23,23,]),'con':([12,18,29,],[25,25,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cnf","S'",1,None,None,None),
  ('cnf -> NOT LPAREN cnf RPAREN','cnf',4,'p_cnf_not','hw.py',215),
  ('cnf -> cnf IMPLY clause','cnf',3,'p_cnf_imply','hw.py',220),
  ('cnf -> cnf OR clause','cnf',3,'p_cnf_or','hw.py',224),
  ('cnf -> cnf AND clause','cnf',3,'p_cnf_and','hw.py',228),
  ('cnf -> clause','cnf',1,'p_cnf_clause','hw.py',235),
  ('clause -> clause OR atom','clause',3,'p_clause_or','hw.py',240),
  ('clause -> atom','clause',1,'p_clause_atom','hw.py',245),
  ('atom -> NOT CONSTANT LPAREN argus RPAREN','atom',5,'p_atom_withnot','hw.py',250),
  ('atom -> CONSTANT LPAREN argus RPAREN','atom',4,'p_atom_withoutnot','hw.py',258),
  ('var -> VARIABLE','var',1,'p_var','hw.py',263),
  ('con -> CONSTANT','con',1,'p_const','hw.py',267),
  ('argu -> var','argu',1,'p_arugs_var','hw.py',271),
  ('argu -> con','argu',1,'p_arugs_con','hw.py',275),
  ('argus -> argus COMA argu','argus',3,'p_arugs_vars','hw.py',279),
  ('argus -> argu','argus',1,'p_arugs_single','hw.py',283),
]
